### ISSUE TITLE
Enhancement: Parse control file by using dpkg for updating old tweaks.

### ISSUE THREAD

**Issue by return** [hako/afto#3]
dpkg utilises a `--field` parameter to parse a control file in a deb archive. This can be used to check for an update on an existing deb in a directory before overwriting it in afto.

**Comment by hako** [comment]
I've noticed that there is a difference between reading the control file directly in a theos project and using `dpkg --field tweak_example.deb`

`cat control`

```
Package: com.yourcompany.tweakexample
Name: TweakExample
Depends: mobilesubstrate
Version: 0.0.1
Architecture: iphoneos-arm
Description: An awesome MobileSubstrate tweak!
Maintainer: foo
Author: foo
Section: Tweaks
```

`dpkg --field tweak_example.deb`

```
Package: com.yourcompany.tweakexample
Name: TweakExample
Depends: mobilesubstrate
Architecture: iphoneos-arm
Description: An awesome MobileSubstrate tweak!
Maintainer: foo
Author: foo
Section: Tweaks
Version: 0.0.1-16
Installed-Size: 88
```

The latter includes **Installed-Size** and the **Version** includes the build number, but everything else is the same.

I'll include this as an enhancement, but I'll also keep the option for manually parsing the control file.

**Comment by hako** [comment]
#4 Implements this now.
