### ISSUE TITLE
[Enhancement]: Sign repository whilst creating/updating afto repo

### ISSUE THREAD

**Issue by return** [hako/afto#5]
Tweaks are signed by the developers PGP key to verify that the tweak was developed by only them. afto should sign tweaks that are to be hosted on an afto created repo.

**Comment by hako** [comment]
I can see this working, but this should be optional since some developers do not have PGP/GPG. Could work like this:

`afto -s <repo>` - signs the repo with a Release.gpg inside the repo.

**Comment by hako** [comment]
Found out that the repo should be signed, not the tweaks. Changed the title to reflect this.

**Comment by return** [comment]
This [commit](https://github.com/hako/afto/commit/3bdd3671bf776c2e35315b1429bcc972cbc46bae) implements the repo signing feature.
